### PR TITLE
Advanced error handling

### LINKED ISSUE #53: Advanced validation and error handling
Right now, if you send a request with an incorrectly formatted JSON object, you get a 400 response, which is great. But if you send a correctly formatted object with invalid data (for example invalid foreign key), you get a 500 response because Prisma throws an error. These errors should be caught and handled. Prisma help [here ](https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors) and [here](https://www.prisma.io/docs/reference/api-reference/error-reference#prismaclientknownrequesterror). Nest help (for returning HTTP status codes) [here](https://docs.nestjs.com/exception-filters).

### PR DESCRIPTION
**Pull request by DannySS123**
- Unique error messages for everything I could find
- Errors are handled in the casl factory or in the controllers

If you make endpoints please follow the same error handling pattern.

closes #53

### CODE REVIEW

File: src/groups/groups.controller.ts [hunk 1]
```diff
@@ -46,11 +48,19 @@ export class GroupsController {
...
-    return this.groupsService.addMember(groupId, user.id, GroupRole.PENDING)
+    try {
+      return await this.groupsService.addMember(
+        groupId,
+        user.id,
+        GroupRole.PENDING,
+      )
+    } catch {
+      throw new HttpException('A csoport nem található!', HttpStatus.NOT_FOUND)
+    }
```
Comment (Tschonti) [inline src/groups/groups.controller.ts]: Other possible error: user is already in the group

File: src/groups/groups.controller.ts [hunk 2]
```diff
@@ -61,20 +71,56 @@ export class GroupsController {
...
     @Param('id', ParseIntPipe) groupId: number,
   ): Promise<CreateManyResponse> {
-    return this.groupsService.addManyMembers(groupId, user.userIds)
+    try {
+      return await this.groupsService.addManyMembers(groupId, user.userIds)
+    } catch (e) {
+      if (e instanceof Prisma.PrismaClientKnownRequestError) {
+        if (e.code === 'P2002') {
+          throw new HttpException(
+            'A felhasználó már tagja a csoportnak! xdd',
```
Comment (Tschonti) [inline src/groups/groups.controller.ts]: 🤣😂🤣

**Review by Tschonti — APPROVED** [review]
Good stuff, thanks for this. Missed a few things here are there, I fixed them but still left a comment.
